CREATE TABLE s284712.GAME (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50),
    is_competitive BOOLEAN NOT NULL
);

CREATE TABLE s284712.CHILD (
    id SERIAL PRIMARY KEY, 
    name VARCHAR(50) NOT NULL,
    age INTEGER DEFAULT 0 CHECK (age >= 0),
    gender BOOLEAN NOT NULL
);

CREATE TABLE s284712.QUESTION (
  id SERIAL,
  content varchar NOT NULL,
  adult_id INTEGER NOT NULL,
  priority INTEGER NOT NULL
);


CREATE TABLE s284712.ADULT (
    id SERIAL PRIMARY KEY, 
    name VARCHAR(50) NOT NULL,
    age INTEGER DEFAULT 0 CHECK (age >= 0),
    gender BOOLEAN NOT NULL
);

CREATE TABLE s284712.GAME_INSTANCE (
    id SERIAL PRIMARY KEY, 
    game_id INTEGER NOT NULL,
    won_child_id INTEGER DEFAULT NULL
    );

CREATE TABLE s284712.GAME_PARTICIPATION (
    child_id INTEGER NOT NULL,
    game_instance_id INTEGER NOT NULL,
    PRIMARY KEY (child_id,game_instance_id)
);

CREATE TABLE s284712.GAME_WATCHING (
    adult_id INTEGER NOT NULL,
    game_instance_id INTEGER NOT NULL,
    PRIMARY KEY (adult_id,game_instance_id)
);

CREATE TABLE s284712.FRIENDSHIP (
    child_id INTEGER NOT NULL,
    adult_id INTEGER NOT NULL,
    power INTEGER NOT NULL,
    PRIMARY KEY (child_id,adult_id)
);

ALTER TABLE s284712.GAME_INSTANCE ADD FOREIGN KEY (game_id) REFERENCES s284712.GAME (id);
ALTER TABLE s284712.GAME_INSTANCE ADD FOREIGN KEY (won_child_id) REFERENCES s284712.CHILD (id);
ALTER TABLE s284712.GAME_PARTICIPATION ADD FOREIGN KEY (game_instance_id) REFERENCES s284712.GAME_INSTANCE (id);
ALTER TABLE s284712.GAME_PARTICIPATION ADD FOREIGN KEY (child_id) REFERENCES s284712.CHILD (id);
ALTER TABLE s284712.GAME_WATCHING ADD FOREIGN KEY (game_instance_id) REFERENCES s284712.GAME_INSTANCE (id);
ALTER TABLE s284712.GAME_WATCHING ADD FOREIGN KEY (adult_id) REFERENCES s284712.ADULT (id);
ALTER TABLE s284712.FRIENDSHIP ADD FOREIGN KEY (child_id) REFERENCES s284712.CHILD (id);
ALTER TABLE s284712.FRIENDSHIP ADD FOREIGN KEY (adult_id) REFERENCES s284712.ADULT (id);
ALTER TABLE s284712.QUESTION ADD FOREIGN KEY (adult_id) REFERENCES s284712.ADULT (id);

